spring:
  application:
    name: rest-with-spring-boot-and-java-erudio
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest-with-spring-boot-and-java-erudio?useTimezone=true&serverTimezone=UTC
    username: root
    password: 123123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
logging: # log do spting boot = SLF4J => SIMPLE LOGGING FACADE FOR JAVA. LOGBACK EM CONJUNTO
  level:
    # root: WARN
    br.com.erudio: DEBUG

    # trace -> debug -> info -> warn -> error
    # logs ajuda a descobrir oque esta acontecendom registram o erro e registram. acompanha o desempenho da produção
#      ações preventidas, logs de debug em dev. e em prod erro e warn
# ajuda bastante na comunicação
# por padrao mostra os infos gerados pelo log back